services:
  ui:
    container_name: frontend
    build:
      context: frontend/.
      dockerfile: Dockerfile-nodeHttp
    ports:
      - "3000:3000"

  api:
    container_name: backend
    build: backend/.
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  postgres:
    container_name: postgres
    image: postgres:14
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=byteme
    ports:
      - "5432:5432"
